name: Deploy de produção

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
  
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/home/brutalzinn/servicos"

    - name: Adicionado chave do Discord
      uses: appleboy/ssh-action@master
      env:
        API_KEY: ${{ secrets.API_KEY }}

      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: API_KEY, ORIGIN, FLASK_PORT
        script: |
          sudo rm -f .env
          echo "API_KEY=$API_KEY" >/home/brutalzinn/servicos/.env
          echo "FLASK_PORT=$FLASK_PORT" >>/home/brutalzinn/servicos/.env
          echo "ORIGIN=$ORIGIN" >>/home/brutalzinn/servicos/.env
          echo "HOST=$host" >>/home/brutalzinn/servicos/.env

    - name: Executando docker compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script_stop: true
        script: |
          cd /home/brutalzinn/servicos
          docker-compose up --force-recreate >> compose.log 2>&1 &